### ISSUE TITLE
Missing recursive on arrays

### ISSUE THREAD

**Issue by TomPradat** [Th3Mouk/rethinkdb-translator#4]
https://github.com/Th3Mouk/rethinkdb-translator/blob/c145d3ac86e98d6676aef2b929bb7243ddb50d08/src/Translate.php#L44

This doesn't work if you have an arrayObject inside of an array :

```
[
    [
        new ArrayObject(),
    ]
]
```

We should recursively iterate on arrays too

**Comment by TomPradat** [comment]
This might cause performance issues though, what do you think ?

**Comment by Th3Mouk** [comment]
This tool must be used with caution, a `pluck` is a better solution when there is performance issue. We can handle this.

**Comment by TomPradat** [comment]
Alright, i'll open a PR then :)
